<a href="https://colab.research.google.com/github/vishwasahuja62-maker/Machine-Learning-Labs/blob/main/Machine_Learning_Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
# Data Frams elements can be heterogeneous
dataset = pd.read_csv('Salary_Dataset.csv')
display(dataset.head())

  country   Salary  YearsExperience Purchased
0   Dubai  39343.0              1.1        No
1  Canada  46205.0              1.3       Yes
2  Canada  37731.0              1.5        No
3  Canada  43525.0              2.0        No
4     USA  39891.0              2.2        No

In [ ]:
# Applying One-Hot Encoding
country_dummy = pd.get_dummies(dataset['country'])

In [ ]:
dataset = pd.concat([dataset, country_dummy], axis = 1)

In [ ]:
dataset.drop('country', axis = 1, inplace = True)

In [ ]:
dataset = dataset[['Australia', 'Canada', 'Dubai', 'USA',
                   'YearsExperience', 'Salary', 'Purchased']]
dataset

    Australia  Canada  Dubai    USA  YearsExperience    Salary Purchased
0       False   False   True  False              1.1   39343.0        No
1       False    True  False  False              1.3   46205.0       Yes
2       False    True  False  False              1.5   37731.0        No
3       False    True  False  False              2.0   43525.0        No
4       False   False  False   True              2.2   39891.0        No
5       False   False   True  False              2.9   56642.0        No
6       False    True  False  False              3.0   60150.0       Yes
7        True   False  False  False              3.2   54445.0        No
8       False   False   True  False              3.2   64445.0       Yes
9       False   False   True  False              3.7   57189.0        No
10      False   False   True  False              3.9   63218.0       Yes
11      False   False  False   True              4.0   55794.0        No
12      False   False   True  False              4.0   56957.0       Yes
13      False    True  False  False              4.1   57081.0        No
14       True   False  False  False              4.5   61111.0        No
15      False   False  False   True              4.9   67938.0        No
16      False   False  False   True              5.1   66029.0        No
17      False    True  False  False              5.3   83088.0        No
18       True   False  False  False              5.9   81363.0       Yes
19      False    True  False  False              6.0   93940.0        No
20      False    True  False  False              6.8   91738.0        No
21       True   False  False  False              7.1   98273.0        No
22       True   False  False  False              7.9  101302.0        No
23       True   False  False  False              8.2  113812.0       Yes
24      False   False   True  False              8.7  109431.0        No
25       True   False  False  False              9.0  105582.0       Yes
26      False   False   True  False              9.5  116969.0        No
27      False   False  False   True              9.6  112635.0       Yes
28      False   False  False   True             10.3  122391.0        No
29      False    True  False  False             10.5  121872.0       Yes